'use client';

import { useMemo, useState } from 'react';
import { CheckCircle2, Clock3, MapPin, Package, RefreshCw, Search, Truck } from 'lucide-react';
import { VivoBrandLogo } from './VivoBrandLogo';
import { useSiteConfig } from './siteConfig';

const shipments = [
  { id: 'CV-2026-1048', title: 'MacBook Pro M3', origin: 'Guatemala City', destination: 'Antigua Guatemala', status: 'In transit', eta: 'Today, 17:40', progress: 68, driver: 'Carlos M.', lastUpdate: '4 min ago', color: 'text-blue-300' },
  { id: 'CV-2026-1047', title: 'Cafe de altura 500g', origin: 'Huehuetenango', destination: 'Zone 10, Guatemala City', status: 'Delivered', eta: 'Delivered 10:25', progress: 100, driver: 'Maria G.', lastUpdate: 'Today, 10:25', color: 'text-emerald-300' },
  { id: 'CV-2026-1046', title: 'Toyota Hilux 2022', origin: 'Mixco', destination: 'Quetzaltenango', status: 'Pickup scheduled', eta: 'Tomorrow, 09:00', progress: 22, driver: 'Assignment pending', lastUpdate: 'Yesterday, 18:20', color: 'text-amber-300' }
];
const statuses = ['All', 'In transit', 'Delivered', 'Pickup scheduled'];

export function CargoVivoTracking() {
  const { config } = useSiteConfig();
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All');
  const [selectedId, setSelectedId] = useState(shipments[0].id);
  const [refreshing, setRefreshing] = useState(false);
  const [message, setMessage] = useState('');
  const selected = shipments.find((shipment) => shipment.id === selectedId) || shipments[0];
  const filtered = useMemo(() => shipments.filter((shipment) => (status === 'All' || shipment.status === status) && `${shipment.id} ${shipment.title} ${shipment.destination}`.toLowerCase().includes(query.toLowerCase())), [query, status]);
  const refresh = () => { if (!config.modules.cargoSimulation) return setMessage('CARGO simulation is currently disabled by site administration.'); setRefreshing(true); window.setTimeout(() => { setRefreshing(false); setMessage('Sample route status refreshed.'); }, 700); };

  return <main className="min-h-screen bg-[#07111c] px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-7xl">
    <header className="flex flex-wrap items-end justify-between gap-5 border-b border-white/10 pb-6"><div><VivoBrandLogo variant="cargo" light href="https://cargovivo.com" /><p className="mt-3 text-xs font-bold tracking-[0.22em] text-sky-300">CARGO VIVO / TRACKING</p><h1 className="mt-2 text-4xl font-extrabold tracking-tight">Every shipment, always visible.</h1><p className="mt-2 max-w-xl text-sm text-white/55">Track packages, review deliveries, and see the next route update.</p></div><button type="button" onClick={refresh} className="inline-flex items-center gap-2 rounded-lg border border-sky-300/30 bg-sky-300/10 px-4 py-3 text-xs font-bold text-sky-200"><RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} />{refreshing ? 'Updating...' : 'Refresh routes'}</button></header>
    {message && <p role="status" className="mt-5 rounded-lg border border-sky-300/25 bg-sky-300/10 p-3 text-sm text-sky-100">{message}</p>}<section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="In transit" value="1" icon={Truck} /><Metric label="Delivered today" value="1" icon={CheckCircle2} /><Metric label="Next pickup" value="Tomorrow 09:00" icon={Clock3} /></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="vivo-glass-panel rounded-xl p-4"><div className="flex flex-wrap gap-2">{statuses.map((item) => <button type="button" key={item} onClick={() => setStatus(item)} className={`rounded-full border px-3 py-2 text-[11px] font-bold ${status === item ? 'border-sky-300 bg-sky-300/15 text-sky-200' : 'border-white/10 text-white/55'}`}>{item}</button>)}</div><label className="mt-4 flex items-center gap-2 rounded-lg border border-white/10 bg-black/20 px-3 py-2"><Search size={16} className="text-white/45" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by ID, product, or destination" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-white/35" /></label><div className="mt-4 space-y-3">{filtered.map((shipment) => <button type="button" key={shipment.id} onClick={() => setSelectedId(shipment.id)} className={`w-full rounded-xl border p-4 text-left ${selectedId === shipment.id ? 'border-sky-300/60 bg-sky-300/10' : 'border-white/10 bg-black/15'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold tracking-[0.14em] text-sky-300">{shipment.id}</p><h2 className="mt-1 font-extrabold">{shipment.title}</h2></div><span className={`text-xs font-bold ${shipment.color}`}>{shipment.status}</span></div><p className="mt-3 text-xs text-white/50">{shipment.origin} to {shipment.destination}</p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-sky-300" style={{ width: `${shipment.progress}%` }} /></div></button>)}{filtered.length === 0 && <p className="p-5 text-center text-sm text-white/50">No shipments found.</p>}</div></div>
      <article className="rounded-xl border border-white/10 bg-[#0c1b2a] p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[0.2em] text-sky-300">LIVE SHIPMENT</p><h2 className="mt-2 text-2xl font-extrabold">{selected.id}</h2><p className="mt-1 text-sm text-white/55">{selected.title}</p></div><Package className="text-sky-300" size={28} /></div><div className="mt-8 rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between text-xs"><span className="text-white/50">Current status</span><strong className={selected.color}>{selected.status}</strong></div><div className="mt-4 h-3 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-sky-400 to-cyan-200" style={{ width: `${selected.progress}%` }} /></div><div className="mt-2 flex justify-between text-[10px] text-white/40"><span>Origin</span><span>{selected.progress}% complete</span><span>Destination</span></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Detail icon={MapPin} label="Route" value={`${selected.origin} to ${selected.destination}`} /><Detail icon={Clock3} label="Estimated delivery" value={selected.eta} /><Detail icon={Truck} label="Driver" value={selected.driver} /><Detail icon={RefreshCw} label="Last update" value={selected.lastUpdate} /></div><button type="button" onClick={refresh} className="mt-6 w-full rounded-lg bg-sky-300 px-4 py-3 text-sm font-bold text-[#07111c]">Refresh route update</button></article>
    </section>
  </div></main>;
}

function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Truck }) { return <article className="vivo-glass-panel rounded-xl p-4"><Icon size={18} className="text-sky-300" /><p className="mt-3 text-xs text-white/50">{label}</p><strong className="mt-1 block text-xl font-extrabold">{value}</strong></article>; }
function Detail({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Truck }) { return <div className="rounded-lg border border-white/10 bg-black/15 p-3"><Icon size={16} className="text-sky-300" /><p className="mt-2 text-[10px] text-white/45">{label}</p><strong className="mt-1 block text-xs">{value}</strong></div>; }
