'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { BarChart3, CheckCircle2, Clock3, Eye, Heart, PackageCheck, Plus, ShieldCheck, Star, Truck, WalletCards, X } from 'lucide-react';
import { getSellerAnalytics } from '../services/sellerService';

type SellerTab = 'storefront' | 'products' | 'orders' | 'shipping' | 'balance';
type SellerProduct = { name: string; category: string; stock: number; price: string; status: string; description: string; mark: string; image?: string };
const initialProducts: SellerProduct[] = [
  { name: 'Café de altura 500g', category: 'Agriculture', stock: 84, price: 'Q 18.00', status: 'Active', description: 'Small-batch Guatemalan coffee, roasted weekly.', mark: 'CA', image: '/images/catalog/coffee.jpg' },
  { name: 'Canasta tejida', category: 'Home', stock: 12, price: 'Q 145.00', status: 'Low stock', description: 'Handwoven basket from local artisans.', mark: 'CT', image: '/images/catalog/home.jpg' },
  { name: 'Miel de abeja', category: 'Agriculture', stock: 0, price: 'Q 42.00', status: 'Sold out', description: 'Pure highland honey in a sealed glass jar.', mark: 'MA' }
];

export function SellerDashboard() {
  const analytics = getSellerAnalytics();
  const [tab, setTab] = useState<SellerTab>('storefront');
  const [products, setProducts] = useState(initialProducts);
  const [category, setCategory] = useState('All');
  const [selected, setSelected] = useState<SellerProduct | null>(null);
  const [editing, setEditing] = useState<SellerProduct | null>(null);
  const [message, setMessage] = useState('');
  const addProduct = () => { const next = { name: 'New product', category: 'Draft', stock: 1, price: 'Q 0.00', status: 'Draft', description: 'Add a product description.', mark: 'NEW' }; setProducts((current) => [next, ...current]); setTab('products'); setMessage(`New product added. Current GMV: Q ${analytics.totalGmvGTQ.toLocaleString('es-GT')}.`); };
  const deleteProduct = (name: string) => { if (!window.confirm(`Remove ${name} from your catalog?`)) return; setProducts((current) => current.filter((product) => product.name !== name)); setSelected(null); setEditing(null); setMessage('Product removed from the catalog.'); };
  const saveProduct = (nextProduct: SellerProduct) => { setProducts((current) => current.map((product) => product.name === editing?.name ? nextProduct : product)); setEditing(null); setMessage('Product details updated.'); };
  const categories = ['All', ...Array.from(new Set(products.map((product) => product.category)))];
  const visibleProducts = useMemo(() => products.filter((product) => category === 'All' || product.category === category), [category, products]);
  return <main className="min-h-screen bg-[#07090D] p-4 text-white sm:p-7"><div className="mx-auto max-w-7xl"><header className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-[#161b25] via-[#0d1117] to-[#FF6A00]/15 p-6 shadow-2xl sm:p-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full border-[32px] border-[#FF6A00]/10" /><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold tracking-[0.2em] text-[#FF6A00]">SELLER STOREFRONT</p><div className="mt-3 flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-[#FF6A00] text-xl font-black text-white">CA</div><div><h1 className="text-3xl font-extrabold tracking-tight">Café Antigua</h1><p className="mt-1 text-sm text-white/55">Guatemala City · Specialty coffee & artisan goods</p><div className="mt-2 flex items-center gap-3 text-xs"><span className="inline-flex items-center gap-1 text-emerald-300"><CheckCircle2 size={14} />Verified seller</span><span className="inline-flex items-center gap-1 text-amber-200"><Star size={14} fill="currentColor" />4.9 rating</span></div></div></div></div><div className="flex gap-2"><Link href="/" className="rounded-lg border border-white/15 px-4 py-3 text-xs font-bold text-white/75">Marketplace</Link><button type="button" onClick={addProduct} className="inline-flex items-center gap-2 rounded-lg bg-[#FF6A00] px-4 py-3 text-xs font-bold"><Plus size={15} />Add product</button></div></div></header><nav className="my-6 flex gap-2 overflow-x-auto" aria-label="Seller workspace"><Tab active={tab === 'storefront'} onClick={() => setTab('storefront')}>Storefront</Tab><Tab active={tab === 'products'} onClick={() => setTab('products')}>Products</Tab><Tab active={tab === 'orders'} onClick={() => setTab('orders')}>Orders</Tab><Tab active={tab === 'shipping'} onClick={() => setTab('shipping')}>Shipping</Tab><Tab active={tab === 'balance'} onClick={() => setTab('balance')}>Balance</Tab></nav>{message && <p role="status" className="mb-4 rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm font-bold text-emerald-200">{message}</p>}{tab === 'storefront' && <Storefront products={visibleProducts} categories={categories} category={category} setCategory={setCategory} onSelect={setSelected} />}{tab === 'products' && <Products products={products} onSelect={setSelected} onEdit={setEditing} onDelete={deleteProduct} onAdd={addProduct} />}{tab === 'orders' && <Orders />}{tab === 'shipping' && <Shipping />}{tab === 'balance' && <Balance />}{selected && <ProductModal product={selected} onClose={() => setSelected(null)} onEdit={() => { setEditing(selected); setSelected(null); }} onDelete={() => deleteProduct(selected.name)} />}{editing && <ProductEditModal product={editing} onClose={() => setEditing(null)} onSave={saveProduct} />}</div></main>;
}

function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: string }) { return <button type="button" onClick={onClick} className={`whitespace-nowrap rounded-lg border px-4 py-2 text-xs font-bold ${active ? 'border-[#FF6A00] bg-[#FF6A00]/15 text-[#FFB38A]' : 'border-white/10 bg-white/[0.04] text-white/55 hover:border-white/25'}`}>{children}</button>; }
function Storefront({ products, categories, category, setCategory, onSelect }: { products: SellerProduct[]; categories: string[]; category: string; setCategory: (value: string) => void; onSelect: (product: SellerProduct) => void }) { return <><section className="grid gap-4 sm:grid-cols-3"><Metric icon={Eye} label="Store views" value="12.8K" trend="+18.6%" /><Metric icon={Heart} label="Saved products" value="428" trend="This month" /><Metric icon={ShieldCheck} label="Trust score" value="98/100" trend="Excellent" /></section><section className="mt-6 rounded-2xl border border-white/10 bg-white/[0.045] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.18em] text-[#FF6A00]">PUBLIC CATALOG</p><h2 className="mt-1 text-2xl font-extrabold">Featured products</h2></div><span className="text-xs text-white/45">{products.length} visible listings</span></div><div className="mt-5 flex gap-2 overflow-x-auto">{categories.map((item) => <button type="button" key={item} onClick={() => setCategory(item)} className={`rounded-full border px-3 py-2 text-[11px] font-bold ${category === item ? 'border-[#FF6A00] bg-[#FF6A00]/15 text-[#FFB38A]' : 'border-white/10 text-white/55'}`}>{item}</button>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <ProductCard key={product.name} product={product} onSelect={() => onSelect(product)} />)}</div></section></>; }
function ProductCard({ product, onSelect }: { product: SellerProduct; onSelect: () => void }) { return <button type="button" onClick={onSelect} className="group rounded-2xl border border-white/10 bg-black/20 p-4 text-left transition hover:-translate-y-1 hover:border-[#FF6A00]/60"><div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-gradient-to-br from-[#1d252f] to-[#0d1117] text-4xl font-black text-[#FF6A00]/60">{product.image ? <img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <span className="grid h-full place-items-center">{product.mark}</span>}</div><p className="mt-4 text-[10px] font-bold tracking-[0.16em] text-[#FF6A00]">{product.category}</p><h3 className="mt-1 font-extrabold">{product.name}</h3><p className="mt-2 text-lg font-bold">{product.price}</p><p className="mt-2 line-clamp-2 text-xs text-white/45">{product.description}</p><span className="mt-4 block text-xs font-bold text-[#FFB38A]">View product details →</span></button>; }
function Products({ products, onSelect, onEdit, onDelete, onAdd }: { products: SellerProduct[]; onSelect: (product: SellerProduct) => void; onEdit: (product: SellerProduct) => void; onDelete: (name: string) => void; onAdd: () => void }) { return <section className="rounded-2xl border border-white/10 bg-white/[0.045] p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[0.18em] text-[#FF6A00]">INVENTORY</p><h2 className="mt-1 text-2xl font-extrabold">Manage products</h2></div><button type="button" onClick={onAdd} className="rounded-lg bg-[#FF6A00] px-4 py-3 text-xs font-bold"><Plus size={14} className="mr-1 inline" />Add product</button></div><div className="mt-5 grid gap-3">{products.map((product) => <div key={product.name} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-white/10 bg-black/20 p-4"><button type="button" onClick={() => onSelect(product)} className="min-w-0 flex-1 text-left"><strong className="block">{product.name}</strong><small className="text-xs text-white/45">{product.stock} in stock · {product.status}</small></button><span className="font-bold text-[#FFB38A]">{product.price}</span><div className="flex gap-2"><button type="button" onClick={() => onEdit(product)} className="rounded-lg border border-white/15 px-3 py-2 text-xs font-bold">Edit</button><button type="button" onClick={() => onDelete(product.name)} className="rounded-lg border border-red-400/30 px-3 py-2 text-xs font-bold text-red-200">Remove</button></div></div>)}</div></section>; }
function ProductModal({ product, onClose, onEdit, onDelete }: { product: SellerProduct; onClose: () => void; onEdit: () => void; onDelete: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-label="Product details" onClick={onClose}><article className="w-full max-w-md rounded-2xl border border-white/10 bg-[#11151C] p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-[#FF6A00]">{product.category}</p><h2 className="mt-2 text-2xl font-extrabold">{product.name}</h2></div><button type="button" onClick={onClose} className="rounded-full border border-white/10 px-3 py-2 text-xs">Close</button></div><div className="mt-6 grid gap-3 text-sm"><p className="text-white/60">{product.description}</p><p><strong>Price:</strong> {product.price}</p><p><strong>Stock:</strong> {product.stock}</p><p><strong>Status:</strong> {product.status}</p></div><div className="mt-6 flex gap-2"><button type="button" onClick={onEdit} className="flex-1 rounded-lg bg-[#FF6A00] px-4 py-3 text-xs font-bold">Edit product</button><button type="button" onClick={onDelete} className="rounded-lg border border-red-400/30 px-4 py-3 text-xs font-bold text-red-200">Remove</button></div></article></div>; }
function ProductEditModal({ product, onClose, onSave }: { product: SellerProduct; onClose: () => void; onSave: (product: SellerProduct) => void }) { const [draft, setDraft] = useState(product); return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-label="Edit product"><form onSubmit={(event) => { event.preventDefault(); onSave(draft); }} className="w-full max-w-md rounded-2xl border border-white/10 bg-[#11151C] p-6 text-white shadow-2xl"><div className="flex items-start justify-between"><h2 className="text-2xl font-extrabold">Edit product</h2><button type="button" onClick={onClose} className="rounded-full border border-white/10 px-3 py-2 text-xs">Close</button></div><label className="mt-5 block text-xs font-bold text-white/60">Product name<input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" /></label><label className="mt-4 block text-xs font-bold text-white/60">Price<input required value={draft.price} onChange={(event) => setDraft({ ...draft, price: event.target.value })} className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" /></label><label className="mt-4 block text-xs font-bold text-white/60">Description<textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} rows={3} className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" /></label><button type="submit" className="mt-6 w-full rounded-lg bg-[#FF6A00] px-4 py-3 text-xs font-bold">Save changes</button></form></div>; }
function Metric({ icon: Icon, label, value, trend }: { icon: typeof Eye; label: string; value: string; trend: string }) { return <article className="rounded-xl border border-white/10 bg-white/[0.045] p-4"><Icon size={18} className="text-[#FF6A00]" /><p className="mt-3 text-xs text-white/45">{label}</p><strong className="mt-1 block text-2xl font-extrabold">{value}</strong><span className="mt-1 block text-[11px] text-emerald-300">{trend}</span></article>; }
function Orders() { return <section className="rounded-2xl border border-white/10 bg-white/[0.045] p-6"><h2 className="text-2xl font-extrabold">Recent orders</h2><div className="mt-5 space-y-3"><div className="flex items-center justify-between rounded-xl border border-white/10 bg-black/20 p-4"><span><strong className="block">#VA-10582 · Café de altura 500g</strong><small className="text-xs text-white/45">Today · VIVO PAY protected</small></span><span className="font-bold text-emerald-300">Q 180.00</span></div><div className="flex items-center justify-between rounded-xl border border-white/10 bg-black/20 p-4"><span><strong className="block">#VA-10581 · MacBook Pro M3</strong><small className="text-xs text-white/45">Today · Ready for shipment</small></span><span className="font-bold text-emerald-300">Q 14,500.00</span></div></div></section>; }
function Shipping() { return <section className="rounded-2xl border border-white/10 bg-white/[0.045] p-6"><h2 className="text-2xl font-extrabold">Shipping operations</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={Truck} label="Ready to ship" value="9" trend="Action needed" /><Metric icon={PackageCheck} label="In transit" value="14" trend="CARGO VIVO" /><Metric icon={CheckCircle2} label="Delivered" value="128" trend="This month" /></div></section>; }
function Balance() { return <section className="rounded-2xl border border-white/10 bg-white/[0.045] p-6"><h2 className="text-2xl font-extrabold">Seller balance</h2><p className="mt-5 text-sm text-white/50">Available for withdrawal</p><strong className="mt-1 block text-4xl font-extrabold text-[#FFB38A]">Q 18,420</strong><button type="button" className="mt-6 rounded-lg bg-[#FF6A00] px-4 py-3 text-sm font-bold">Request payout</button></section>; }