'use client';

import { Paintbrush, PanelsTopLeft, SlidersHorizontal } from 'lucide-react';
import { SiteConfig, useSiteConfig } from './siteConfig';

export function SiteConfigManager() {
  const { config, updateConfig } = useSiteConfig();
  const current = config;
  const update = (next: SiteConfig) => updateConfig(next);
  return <section className="vivo-public-shell px-4 pb-6 pt-2 text-white sm:px-6"><div className="mx-auto max-w-7xl"><div className="vivo-glass-panel rounded-xl p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.16em] text-[#FF6A00]">DYNAMIC CMS</p><h2 className="mt-2 text-2xl font-extrabold">Site controls</h2><p className="mt-1 text-sm text-white/60">Changes save instantly in this browser and other open VIVO AMIGO tabs.</p></div><span className="rounded-lg border border-emerald-300/25 bg-emerald-300/10 px-4 py-3 text-xs font-bold text-emerald-200">Auto-save active</span></div><div className="mt-6 grid gap-5 lg:grid-cols-3"><ConfigGroup icon={PanelsTopLeft} title="Header & footer"><Field label="Announcement" value={current.announcement} onChange={(announcement) => update({ ...current, announcement })} /><Field label="Footer text" value={current.footerText} onChange={(footerText) => update({ ...current, footerText })} /><Field label="PAY navigation" value={current.navigation.pay} onChange={(pay) => update({ ...current, navigation: { ...current.navigation, pay } })} /><Field label="CARGO navigation" value={current.navigation.cargo} onChange={(cargo) => update({ ...current, navigation: { ...current.navigation, cargo } })} /></ConfigGroup><ConfigGroup icon={Paintbrush} title="Theme & motion"><label className="block text-xs font-bold text-white/70">Orange accent<input value={current.accent} onChange={(event) => update({ ...current, accent: event.target.value })} className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-sm" /></label><Range label="Glass opacity" value={current.glassOpacity} min={0.02} max={0.18} step={0.005} onChange={(glassOpacity) => update({ ...current, glassOpacity })} /><Range label="Motion speed" value={current.motionSpeed} min={100} max={400} step={10} onChange={(motionSpeed) => update({ ...current, motionSpeed })} /></ConfigGroup><ConfigGroup icon={SlidersHorizontal} title="Module toggles"><Toggle label="Marketplace preview" checked={current.modules.marketplacePreview} onChange={(marketplacePreview) => update({ ...current, modules: { ...current.modules, marketplacePreview } })} /><Toggle label="VIVO PAY preview" checked={current.modules.payPreview} onChange={(payPreview) => update({ ...current, modules: { ...current.modules, payPreview } })} /><Toggle label="CARGO simulation" checked={current.modules.cargoSimulation} onChange={(cargoSimulation) => update({ ...current, modules: { ...current.modules, cargoSimulation } })} /></ConfigGroup></div></div></div></section>;
}

function ConfigGroup({ icon: Icon, title, children }: { icon: typeof PanelsTopLeft; title: string; children: React.ReactNode }) { return <div className="rounded-lg border border-white/10 bg-black/15 p-4"><div className="flex items-center gap-2"><Icon size={16} className="text-[#FF6A00]" /><h3 className="text-sm font-extrabold">{title}</h3></div><div className="mt-4 space-y-4">{children}</div></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-xs font-bold text-white/70">{label}<textarea value={value} rows={label === 'Announcement' ? 3 : 2} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full resize-none rounded-lg border border-white/10 bg-black/20 p-3 text-sm font-normal" /></label>; }
function Range({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void }) { return <label className="block text-xs font-bold text-white/70">{label}<span className="float-right text-[#FFB38A]">{value}</span><input type="range" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Number(event.target.value))} className="mt-3 w-full accent-[#FF6A00]" /></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex items-center justify-between gap-3 text-sm font-semibold"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-5 w-5 accent-[#FF6A00]" /></label>; }
