import React from 'react';
import { VivoSecurityShieldDashboard } from './VivoSecurityShieldDashboard';

export const VivoPremiumShowcase = () => (
  <div className="relative min-h-screen overflow-hidden bg-[#070312] font-sans text-white selection:bg-purple-500 selection:text-white">
    <div className="pointer-events-none absolute left-1/2 top-0 h-[400px] w-[800px] -translate-x-1/2 bg-gradient-to-b from-purple-600/20 via-indigo-600/10 to-transparent blur-[120px]" />
    <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6" aria-label="VIVO AMIGO premium navigation">
      <a href="/" className="flex items-center gap-3" aria-label="vivoamigo home"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-purple-500 to-indigo-600 p-px font-black"><span className="flex h-full w-full items-center justify-center rounded-[15px] bg-[#070312] text-purple-300">V</span></span><span className="text-xl font-bold tracking-tight">vivo<span className="font-extrabold text-purple-400">amigo</span></span></a>
      <div className="flex items-center gap-4"><button type="button" className="px-4 py-2 text-xs font-semibold text-gray-400 transition-colors hover:text-white">Iniciar Sesión</button><button type="button" className="rounded-full bg-white px-5 py-2.5 text-xs font-bold text-black shadow-lg shadow-white/10 transition-all hover:bg-gray-200">Explorar Plataforma</button></div>
    </nav>
    <main className="relative z-10 mx-auto max-w-7xl px-6 pb-24 pt-16">
      <div className="mx-auto max-w-3xl space-y-6 text-center"><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-3.5 py-1.5 backdrop-blur-md"><span className="h-2 w-2 animate-pulse rounded-full bg-purple-400" /><span className="text-xs font-medium uppercase tracking-wide text-purple-300">Ecosistema Digital de Guatemala</span></div><h1 className="bg-gradient-to-b from-white via-white/90 to-white/50 bg-clip-text text-5xl font-extrabold leading-[1.1] tracking-tight text-transparent md:text-7xl">Comercio Seguro, Garantizado y Sin Riesgos.</h1><p className="mx-auto max-w-xl text-base font-normal leading-relaxed text-gray-400">La plataforma líder con respaldo Escrow <strong>VIVO-CHECK</strong>, auxilio vial 24/7 <strong>VIVO-ASSIST</strong> y verificación de identidad oficial.</p></div>
      <div className="mt-16 grid grid-cols-1 gap-6 md:grid-cols-3">
        <article className="group relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-b from-white/[0.08] to-white/[0.02] p-8 backdrop-blur-xl transition-all duration-500 hover:border-purple-500/40 md:col-span-2"><div className="pointer-events-none absolute right-0 top-0 h-64 w-64 rounded-full bg-purple-500/10 blur-3xl transition-all duration-500 group-hover:bg-purple-500/20" /><span className="font-mono text-xs font-semibold uppercase tracking-wider text-purple-400">Garantía Escrow</span><h2 className="mb-3 mt-2 text-2xl font-bold text-white">VIVO-CHECK &amp; Depósito de Seguridad</h2><p className="mb-6 max-w-md text-sm leading-relaxed text-gray-400">El dinero permanece retenido en una cuenta escrow segura hasta que el comprador verifica y aprueba la entrega con código biométrico OTP.</p><div className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#0D061F] p-4 shadow-2xl"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-purple-500/30 bg-purple-500/20 text-purple-300">Shield</span><div><p className="text-xs font-bold text-white">Estado de Fondos</p><p className="text-[10px] text-gray-400">Protegido por Escrow Automático</p></div></div><span className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 font-mono text-xs font-bold text-emerald-400">Q2,500.00 Retenido</span></div></article>
        <article className="group relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-b from-white/[0.08] to-white/[0.02] p-8 backdrop-blur-xl transition-all duration-500 hover:border-purple-500/40"><span className="font-mono text-xs font-semibold uppercase tracking-wider text-purple-400">Auxilio Vial</span><h2 className="mb-3 mt-2 text-xl font-bold text-white">VIVO-ASSIST 24/7</h2><p className="mb-6 text-xs leading-relaxed text-gray-400">Asistencia inmediata en carretera con precio fijo transparente y rastreo GPS en tiempo real.</p><button type="button" className="w-full rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 py-3 text-xs font-bold text-white shadow-lg shadow-purple-600/30 transition-all hover:from-purple-500 hover:to-indigo-500">Solicitar Grúa / Auxilio</button></article>
      </div>
      <VivoSecurityShieldDashboard />
    </main>
  </div>
);
