'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { registerOwner } from '@/components/adminBrowserAuth';

export default function RegisterAdmin() {
 const [error, setError] = useState('');
 const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get('password')); if (password !== form.get('confirmPassword')) return setError('Passwords do not match.'); if (password.length < 12) return setError('Use at least 12 characters.'); try { await registerOwner(String(form.get('name')), String(form.get('email')), password); window.location.assign('/admin/login'); } catch (err) { setError(err instanceof Error ? err.message : 'Registration failed.'); } };
 return <main className="vivo-public-shell grid min-h-screen place-items-center p-4 text-white"><form onSubmit={submit} className="vivo-glass-dialog w-full max-w-md rounded-xl p-7"><p className="text-xs font-bold tracking-[.16em] text-[#FF6A00]">VIVO AMIGO</p><h1 className="mt-2 text-3xl font-extrabold">Create Super Admin account</h1><p className="mt-2 text-sm text-white/60">One owner account for this browser.</p>{error && <p role="alert" className="mt-4 text-sm text-red-300">{error}</p>}<label className="mt-5 block text-xs font-bold">Full name<input name="name" defaultValue="SERDAR CEVIK" required className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3" /></label><label className="mt-4 block text-xs font-bold">Email<input name="email" type="email" required className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3" /></label><label className="mt-4 block text-xs font-bold">Create password<input name="password" type="password" required className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3" /></label><label className="mt-4 block text-xs font-bold">Confirm password<input name="confirmPassword" type="password" required className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3" /></label><button className="mt-6 w-full rounded-lg bg-[#FF6A00] p-3 font-bold">Create account</button><Link href="/admin/login" className="mt-4 block text-center text-sm text-[#FFB38A]">Already registered? Sign in</Link></form></main>;
}
